% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Actividad2:Estimación del modelo lineal},
  pdfauthor={María Sánchez Paniagua},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Actividad2:Estimación del modelo lineal}
\author{María Sánchez Paniagua}
\date{2024-03-17}

\begin{document}
\maketitle

\hypertarget{ejercicios-del-libro-de-faraway}{%
\section{Ejercicios del libro de
Faraway}\label{ejercicios-del-libro-de-faraway}}

\hypertarget{ejercicio-1-cap.-2-puxe1g.-30}{%
\subsection{1. (Ejercicio 1 cap. 2 pág.
30)}\label{ejercicio-1-cap.-2-puxe1g.-30}}

The dataset teengamb concerns a study of teenage gambling in Britain.
Fit a regression model with the expenditure on gambling as the response
and the sex, status, income and verbal score as predictors. Present the
output.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(faraway)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'faraway' was built under R version 4.3.3
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(teengamb)}
\NormalTok{modelo }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(gamble }\SpecialCharTok{\textasciitilde{}}\NormalTok{ sex }\SpecialCharTok{+}\NormalTok{ status }\SpecialCharTok{+}\NormalTok{ income }\SpecialCharTok{+}\NormalTok{ verbal, }\AttributeTok{data =}\NormalTok{ teengamb)}
\NormalTok{modelo}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = gamble ~ sex + status + income + verbal, data = teengamb)
## 
## Coefficients:
## (Intercept)          sex       status       income       verbal  
##    22.55565    -22.11833      0.05223      4.96198     -2.95949
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(modelo)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = gamble ~ sex + status + income + verbal, data = teengamb)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -51.082 -11.320  -1.451   9.452  94.252 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept)  22.55565   17.19680   1.312   0.1968    
## sex         -22.11833    8.21111  -2.694   0.0101 *  
## status        0.05223    0.28111   0.186   0.8535    
## income        4.96198    1.02539   4.839 1.79e-05 ***
## verbal       -2.95949    2.17215  -1.362   0.1803    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 22.69 on 42 degrees of freedom
## Multiple R-squared:  0.5267, Adjusted R-squared:  0.4816 
## F-statistic: 11.69 on 4 and 42 DF,  p-value: 1.815e-06
\end{verbatim}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\tightlist
\item
  What percentage of variation in the response is explained by these
  predictors?
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{R\_cuadrado }\OtherTok{\textless{}{-}} \FunctionTok{summary}\NormalTok{(modelo)}\SpecialCharTok{$}\NormalTok{r.squared }\SpecialCharTok{*} \DecValTok{100}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Porcentaje de variación explicada"}\NormalTok{, }\FunctionTok{round}\NormalTok{(R\_cuadrado), }\StringTok{"\%}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Porcentaje de variación explicada 53 %
\end{verbatim}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  Which observation has the largest (positive) residual? Give the case
  number.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{residuos }\OtherTok{\textless{}{-}}\FunctionTok{residuals}\NormalTok{(modelo)}
\FunctionTok{cat}\NormalTok{(}\StringTok{"El mayor residuo es "}\NormalTok{, }\FunctionTok{which.max}\NormalTok{(residuos), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## El mayor residuo es  24
\end{verbatim}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
  Compute the mean and median of the residuals.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{media\_residuos }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(}\FunctionTok{residuals}\NormalTok{(modelo))}
\NormalTok{mediana\_residuos }\OtherTok{\textless{}{-}} \FunctionTok{median}\NormalTok{(}\FunctionTok{residuals}\NormalTok{(modelo))}
\end{Highlighting}
\end{Shaded}

La media de los residuos es \ensuremath{-1.5569143\times 10^{-16}} y la
mediana -1.4513921

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{3}
\tightlist
\item
  Compute the correlation of the residuals with the fitted values.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{corr}\OtherTok{\textless{}{-}} \FunctionTok{cor}\NormalTok{(}\FunctionTok{residuals}\NormalTok{(modelo), }\FunctionTok{fitted}\NormalTok{(modelo))}
\end{Highlighting}
\end{Shaded}

La correlación de los residuos con los valores ajustados:
\ensuremath{-6.2158235\times 10^{-17}}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{4}
\tightlist
\item
  Compute the correlation of the residuals with the income.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{corr }\OtherTok{\textless{}{-}} \FunctionTok{cor}\NormalTok{(}\FunctionTok{residuals}\NormalTok{(modelo), teengamb}\SpecialCharTok{$}\NormalTok{income)}
\end{Highlighting}
\end{Shaded}

La correlación de los residuos con el ingreso:
\ensuremath{3.2470578\times 10^{-17}}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{5}
\tightlist
\item
  For all other predictors held constant, what would be the difference
  in predicted expenditure on gambling for a male compared to a female?
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{modelo }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(gamble }\SpecialCharTok{\textasciitilde{}}\NormalTok{ sex }\SpecialCharTok{+}\NormalTok{ status }\SpecialCharTok{+}\NormalTok{ income }\SpecialCharTok{+}\NormalTok{ verbal, }\AttributeTok{data =}\NormalTok{ teengamb)}
\NormalTok{coeficientes }\OtherTok{\textless{}{-}} \FunctionTok{coef}\NormalTok{(modelo)}
\NormalTok{coeficientes}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  (Intercept)          sex       status       income       verbal 
##  22.55565063 -22.11833009   0.05223384   4.96197922  -2.95949350
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{diferencia\_prediccion }\OtherTok{\textless{}{-}} \FunctionTok{abs}\NormalTok{(coeficientes[}\StringTok{"sex"}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

Diferencia en el gasto predicho para hombres vs.~mujeres: 22.1183301.

\hypertarget{ejercicio-2-cap.-2-puxe1g.-30}{%
\subsection{2. (Ejercicio 2 cap. 2 pág.
30)}\label{ejercicio-2-cap.-2-puxe1g.-30}}

The dataset uswages is drawn as a sample from the Current Population
Survey in 1988. Fit a model with weekly wages as the response and years
of education and experience as predictors. Report and give a simple
interpretation to the regression coefficient for years of education. Now
fit the same model but with logged weekly wages. Give an interpretation
to the regression coefficient for years of education. Which
interpretation is more natural?

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(uswages)}
\NormalTok{modelo1 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(wage }\SpecialCharTok{\textasciitilde{}}\NormalTok{ educ }\SpecialCharTok{+}\NormalTok{ exper, }\AttributeTok{data =}\NormalTok{ uswages)}
\FunctionTok{summary}\NormalTok{(modelo1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = wage ~ educ + exper, data = uswages)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -1018.2  -237.9   -50.9   149.9  7228.6 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept) -242.7994    50.6816  -4.791 1.78e-06 ***
## educ          51.1753     3.3419  15.313  < 2e-16 ***
## exper          9.7748     0.7506  13.023  < 2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 427.9 on 1997 degrees of freedom
## Multiple R-squared:  0.1351, Adjusted R-squared:  0.1343 
## F-statistic:   156 on 2 and 1997 DF,  p-value: < 2.2e-16
\end{verbatim}

El salario semanal aumenta en promedio en \$51.1753 por cada año de
educación

Segunda interpretacion:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{modelo2 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(}\FunctionTok{log}\NormalTok{(wage) }\SpecialCharTok{\textasciitilde{}}\NormalTok{ educ }\SpecialCharTok{+}\NormalTok{ exper, }\AttributeTok{data =}\NormalTok{ uswages)}
\FunctionTok{summary}\NormalTok{(modelo2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = log(wage) ~ educ + exper, data = uswages)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.7533 -0.3495  0.1068  0.4381  3.5699 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept) 4.650319   0.078354   59.35   <2e-16 ***
## educ        0.090506   0.005167   17.52   <2e-16 ***
## exper       0.018079   0.001160   15.58   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.6615 on 1997 degrees of freedom
## Multiple R-squared:  0.1749, Adjusted R-squared:  0.174 
## F-statistic: 211.6 on 2 and 1997 DF,  p-value: < 2.2e-16
\end{verbatim}

Se espera que un año adicional de educación esté asociado con un aumento
del 9.05 en el salario semanal.

\hypertarget{ejercicio-4-cap.-2-puxe1g.-30}{%
\subsection{4. (Ejercicio 4 cap. 2 pág.
30)}\label{ejercicio-4-cap.-2-puxe1g.-30}}

The dataset prostate comes from a study on 97 men with prostate cancer
who were due to receive a radical prostatectomy.

Fit a model with lpsa as the response and lcavol as the predictor.
Record the residual standard error and the R2.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(prostate)}
\NormalTok{modelo\_1 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(lpsa }\SpecialCharTok{\textasciitilde{}}\NormalTok{ lcavol, }\AttributeTok{data =}\NormalTok{ prostate)}
\FunctionTok{summary}\NormalTok{(modelo\_1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = lpsa ~ lcavol, data = prostate)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.67625 -0.41648  0.09859  0.50709  1.89673 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)  1.50730    0.12194   12.36   <2e-16 ***
## lcavol       0.71932    0.06819   10.55   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.7875 on 95 degrees of freedom
## Multiple R-squared:  0.5394, Adjusted R-squared:  0.5346 
## F-statistic: 111.3 on 1 and 95 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Error estándar residual y el R2 del modelo inicial}
\NormalTok{error\_residual }\OtherTok{\textless{}{-}} \FunctionTok{summary}\NormalTok{(modelo\_1)}\SpecialCharTok{$}\NormalTok{sigma}
\NormalTok{r\_cuadrado }\OtherTok{\textless{}{-}} \FunctionTok{summary}\NormalTok{(modelo\_1)}\SpecialCharTok{$}\NormalTok{r.squared}

\CommentTok{\# Guardo los resultados en un dataframe al que iré añadiendo las variables de cada modelo}
\NormalTok{resultados\_df }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{variable =} \StringTok{"lcavol"}\NormalTok{, }\AttributeTok{error\_residual =}\NormalTok{ error\_residual, }\AttributeTok{r\_cuadrado =}\NormalTok{ r\_cuadrado)}
\end{Highlighting}
\end{Shaded}

Now add lweight, svi, lbph, age, lcp, pgg45 and gleason to the model one
at a time. For each model record the residual standard error and the R2.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{variables }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"lweight"}\NormalTok{, }\StringTok{"svi"}\NormalTok{, }\StringTok{"lbph"}\NormalTok{, }\StringTok{"age"}\NormalTok{, }\StringTok{"lcp"}\NormalTok{, }\StringTok{"pgg45"}\NormalTok{, }\StringTok{"gleason"}\NormalTok{)}

\CommentTok{\# Ajustar los modelos y registrar los resultados en el df por cada variable}
\ControlFlowTok{for}\NormalTok{ (variable }\ControlFlowTok{in}\NormalTok{ variables) \{}
\NormalTok{  modelo\_x }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(}\FunctionTok{paste}\NormalTok{(}\StringTok{"lpsa \textasciitilde{} lcavol +"}\NormalTok{, variable), }\AttributeTok{data =}\NormalTok{ prostate)}
\NormalTok{  error\_residual }\OtherTok{\textless{}{-}} \FunctionTok{summary}\NormalTok{(modelo\_x)}\SpecialCharTok{$}\NormalTok{sigma}
\NormalTok{  r\_cuadrado }\OtherTok{\textless{}{-}} \FunctionTok{summary}\NormalTok{(modelo\_x)}\SpecialCharTok{$}\NormalTok{r.squared}
\NormalTok{  resultados\_df }\OtherTok{\textless{}{-}} \FunctionTok{rbind}\NormalTok{(resultados\_df, }\FunctionTok{data.frame}\NormalTok{(}\AttributeTok{variable =}\NormalTok{ variable, }\AttributeTok{error\_residual =}\NormalTok{ error\_residual, }\AttributeTok{r\_cuadrado =}\NormalTok{ r\_cuadrado))}
\NormalTok{\}}

\NormalTok{resultados\_df}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   variable error_residual r_cuadrado
## 1   lcavol      0.7874994  0.5394319
## 2  lweight      0.7506469  0.5859345
## 3      svi      0.7556684  0.5803761
## 4     lbph      0.7694222  0.5649622
## 5      age      0.7916601  0.5394517
## 6      lcp      0.7872559  0.5445618
## 7    pgg45      0.7801855  0.5527057
## 8  gleason      0.7888801  0.5426807
\end{verbatim}

Plot the trends in these two statistics:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'ggplot2' was built under R version 4.3.2
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(resultados\_df, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ variable)) }\SpecialCharTok{+}
  \FunctionTok{geom\_line}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y =}\NormalTok{ r\_cuadrado }\SpecialCharTok{*} \DecValTok{100}\NormalTok{, }\AttributeTok{group =} \DecValTok{1}\NormalTok{), }\AttributeTok{color =} \StringTok{"pink"}\NormalTok{, }\AttributeTok{size =} \DecValTok{2}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x =} \StringTok{"Variable"}\NormalTok{, }\AttributeTok{y =} \StringTok{"R\^{}2 (\%)"}\NormalTok{, }\AttributeTok{title =} \StringTok{"Tendencias en R\^{}2 por Variable"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
## i Please use `linewidth` instead.
## This warning is displayed once every 8 hours.
## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
## generated.
\end{verbatim}

\includegraphics{Estimación-del-modelo-lineal_files/figure-latex/unnamed-chunk-12-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(resultados\_df, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ variable)) }\SpecialCharTok{+}
  \FunctionTok{geom\_bar}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y =}\NormalTok{ error\_residual), }\AttributeTok{stat =} \StringTok{"identity"}\NormalTok{, }\AttributeTok{fill =} \StringTok{"pink"}\NormalTok{, }\AttributeTok{alpha =} \FloatTok{0.7}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x =} \StringTok{"Variable"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Error Residual"}\NormalTok{, }\AttributeTok{title =} \StringTok{"Tendencias en Error Residualpor Variable"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Estimación-del-modelo-lineal_files/figure-latex/unnamed-chunk-13-1.pdf}

\hypertarget{ejercicio-5-cap.-2-puxe1g.-30}{%
\subsection{5. (Ejercicio 5 cap. 2 pág.
30)}\label{ejercicio-5-cap.-2-puxe1g.-30}}

Using the prostate data, plot lpsa against lcavol.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(prostate)}

\CommentTok{\# Dispersión de lpsa en lcavol}
\FunctionTok{plot}\NormalTok{(prostate}\SpecialCharTok{$}\NormalTok{lcavol, prostate}\SpecialCharTok{$}\NormalTok{lpsa, }\AttributeTok{xlab =} \StringTok{"lcavol"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"lpsa"}\NormalTok{, }\AttributeTok{main =} \StringTok{"lpsa vs lcavol"}\NormalTok{, }\AttributeTok{col =} \StringTok{"grey"}\NormalTok{, }\AttributeTok{pch =} \DecValTok{16}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Estimación-del-modelo-lineal_files/figure-latex/unnamed-chunk-14-1.pdf}

Fit the regressions of lpsa on lcavol and lcavol on lpsa. Display both
regression lines on the plot. At what point do the two lines intersect?

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(prostate}\SpecialCharTok{$}\NormalTok{lcavol, prostate}\SpecialCharTok{$}\NormalTok{lpsa, }\AttributeTok{xlab =} \StringTok{"lcavol"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"lpsa"}\NormalTok{, }\AttributeTok{main =} \StringTok{"lpsa vs lcavol"}\NormalTok{, }\AttributeTok{col =} \StringTok{"grey"}\NormalTok{, }\AttributeTok{pch =} \DecValTok{16}\NormalTok{)}

\CommentTok{\# Regresión de lpsa en lcavol}
\NormalTok{modelo\_lpsa\_lcavol }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(lpsa }\SpecialCharTok{\textasciitilde{}}\NormalTok{ lcavol, }\AttributeTok{data =}\NormalTok{ prostate)}
\FunctionTok{abline}\NormalTok{(modelo\_lpsa\_lcavol, }\AttributeTok{col =} \StringTok{"red"}\NormalTok{)}

\CommentTok{\# Regresión de lcavol en lpsa}
\NormalTok{modelo\_lcavol\_lpsa }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(lcavol }\SpecialCharTok{\textasciitilde{}}\NormalTok{ lpsa, }\AttributeTok{data =}\NormalTok{ prostate)}
\FunctionTok{abline}\NormalTok{(modelo\_lcavol\_lpsa, }\AttributeTok{col =} \StringTok{"green"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Estimación-del-modelo-lineal_files/figure-latex/unnamed-chunk-15-1.pdf}

Para calcular la intersección hay que hacer un sistema de ecuaciones;
lpsa = m1 * lcavol + c1 lcavol = m2 * lpsa + c2 =

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Calculamos el punto de intersección de las dos rectas}
\NormalTok{m1 }\OtherTok{\textless{}{-}} \FunctionTok{coef}\NormalTok{(modelo\_lpsa\_lcavol)[}\StringTok{"lcavol"}\NormalTok{]}
\NormalTok{c1 }\OtherTok{\textless{}{-}} \FunctionTok{coef}\NormalTok{(modelo\_lpsa\_lcavol)[}\StringTok{"(Intercept)"}\NormalTok{]}
\NormalTok{m2 }\OtherTok{\textless{}{-}} \FunctionTok{coef}\NormalTok{(modelo\_lcavol\_lpsa)[}\StringTok{"lpsa"}\NormalTok{]}
\NormalTok{c2 }\OtherTok{\textless{}{-}} \FunctionTok{coef}\NormalTok{(modelo\_lcavol\_lpsa)[}\StringTok{"(Intercept)"}\NormalTok{]}


\CommentTok{\# Calcular el punto de intersección}
\NormalTok{lcavol\_interseccion }\OtherTok{\textless{}{-}}\NormalTok{ (c2 }\SpecialCharTok{{-}}\NormalTok{ c1) }\SpecialCharTok{/}\NormalTok{ (m1 }\SpecialCharTok{{-}}\NormalTok{ m2)}
\NormalTok{lpsa\_interseccion }\OtherTok{\textless{}{-}}\NormalTok{ m1 }\SpecialCharTok{*}\NormalTok{ lcavol\_interseccion }\SpecialCharTok{+}\NormalTok{ c1}


\FunctionTok{cat}\NormalTok{(}\StringTok{"Punto de intersección: (lcavol ="}\NormalTok{, lcavol\_interseccion, }\StringTok{", lpsa ="}\NormalTok{, lpsa\_interseccion, }\StringTok{")"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Punto de intersección: (lcavol = 65.88061 , lpsa = 48.89655 )
\end{verbatim}

Grafico la intersección:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(prostate}\SpecialCharTok{$}\NormalTok{lcavol, prostate}\SpecialCharTok{$}\NormalTok{lpsa, }\AttributeTok{xlab =} \StringTok{"lcavol"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"lpsa"}\NormalTok{, }\AttributeTok{main =} \StringTok{"lpsa vs lcavol"}\NormalTok{, }\AttributeTok{col =} \StringTok{"grey"}\NormalTok{, }\AttributeTok{pch =} \DecValTok{16}\NormalTok{,  }\AttributeTok{ylim =} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{55}\NormalTok{), }\AttributeTok{xlim =} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{69}\NormalTok{))}

\CommentTok{\# Ajustar la regresión de lpsa en lcavol}
\NormalTok{modelo\_lpsa\_lcavol }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(lpsa }\SpecialCharTok{\textasciitilde{}}\NormalTok{ lcavol, }\AttributeTok{data =}\NormalTok{ prostate)}
\FunctionTok{abline}\NormalTok{(modelo\_lpsa\_lcavol, }\AttributeTok{col =} \StringTok{"red"}\NormalTok{)}

\CommentTok{\# Ajustar la regresión de lcavol en lpsa}
\NormalTok{modelo\_lcavol\_lpsa }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(lcavol }\SpecialCharTok{\textasciitilde{}}\NormalTok{ lpsa, }\AttributeTok{data =}\NormalTok{ prostate)}
\FunctionTok{abline}\NormalTok{(modelo\_lcavol\_lpsa, }\AttributeTok{col =} \StringTok{"green"}\NormalTok{)}

\CommentTok{\# Agregar el punto de intersección }
\FunctionTok{points}\NormalTok{(lcavol\_interseccion, lpsa\_interseccion, }\AttributeTok{col =} \StringTok{"orange"}\NormalTok{, }\AttributeTok{pch =} \DecValTok{16}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Estimación-del-modelo-lineal_files/figure-latex/unnamed-chunk-17-1.pdf}

\hypertarget{ejercicio-6-cap.-2-puxe1g.-30}{%
\subsection{6. (Ejercicio 6 cap. 2 pág.
30)}\label{ejercicio-6-cap.-2-puxe1g.-30}}

Thirty samples of cheddar cheese were analyzed for their content of
acetic acid, hydrogen sulfide and lactic acid. Each sample was tasted
and scored by a panel of judges and the average taste score produced.
Use the cheddar data to answer the following:

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\tightlist
\item
  Fit a regression model with taste as the response and the three
  chemical contents as predictors. Report the values of the regression
  coefficients.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(cheddar)}
\NormalTok{modelo }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(taste }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Acetic }\SpecialCharTok{+}\NormalTok{ H2S }\SpecialCharTok{+}\NormalTok{ Lactic, }\AttributeTok{data =}\NormalTok{ cheddar)}

\CommentTok{\# Valores de los coeficientes de regresión}
\NormalTok{coeficientes }\OtherTok{\textless{}{-}} \FunctionTok{coef}\NormalTok{(modelo)}
\FunctionTok{print}\NormalTok{(coeficientes)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## (Intercept)      Acetic         H2S      Lactic 
## -28.8767696   0.3277413   3.9118411  19.6705434
\end{verbatim}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  Compute the correlation between the fitted values and the response.
  Square it. Identify where this value appears in the regression output.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cor\_fitted\_response }\OtherTok{\textless{}{-}} \FunctionTok{cor}\NormalTok{(}\FunctionTok{predict}\NormalTok{(modelo), cheddar}\SpecialCharTok{$}\NormalTok{taste)}
\NormalTok{cor\_sq }\OtherTok{\textless{}{-}}\NormalTok{ cor\_fitted\_response}\SpecialCharTok{\^{}}\DecValTok{2}
\FunctionTok{print}\NormalTok{(cor\_sq)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.6517747
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(modelo)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = taste ~ Acetic + H2S + Lactic, data = cheddar)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -17.390  -6.612  -1.009   4.908  25.449 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)   
## (Intercept) -28.8768    19.7354  -1.463  0.15540   
## Acetic        0.3277     4.4598   0.073  0.94198   
## H2S           3.9118     1.2484   3.133  0.00425 **
## Lactic       19.6705     8.6291   2.280  0.03108 * 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 10.13 on 26 degrees of freedom
## Multiple R-squared:  0.6518, Adjusted R-squared:  0.6116 
## F-statistic: 16.22 on 3 and 26 DF,  p-value: 3.81e-06
\end{verbatim}

Este valor aparece como ``Multiple R squared''

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
  Fit the same regression model but without an intercept term. What is
  the value of R2 reported in the output? Compute a more reasonable
  measure of the good- ness of fit for this example.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{modelo\_si }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(taste }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Acetic }\SpecialCharTok{+}\NormalTok{H2S }\SpecialCharTok{+}\NormalTok{ Lactic }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{, }\AttributeTok{data =}\NormalTok{ cheddar)}
\NormalTok{r2\_si }\OtherTok{\textless{}{-}} \FunctionTok{summary}\NormalTok{(modelo\_si)}\SpecialCharTok{$}\NormalTok{r.squared}
\FunctionTok{cat}\NormalTok{(}\StringTok{"EL valor de R cuadrado sin intercepto es"}\NormalTok{, r2\_si, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## EL valor de R cuadrado sin intercepto es 0.8877059
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Calcular una medida de la bondad del ajuste {-}{-}\textgreater{} R cuadrado ajustado}
\NormalTok{r\_cuadrado\_ajustado }\OtherTok{\textless{}{-}} \FunctionTok{summary}\NormalTok{(modelo\_si)}\SpecialCharTok{$}\NormalTok{adj.r.squared}

\FunctionTok{cat}\NormalTok{(}\StringTok{"EL valor de R cuadrado  es"}\NormalTok{, r\_cuadrado\_ajustado, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## EL valor de R cuadrado  es 0.8752288
\end{verbatim}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{3}
\tightlist
\item
  Compute the regression coefficients from the original fit using the QR
  decomposition showing your R code.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{X }\OtherTok{\textless{}{-}} \FunctionTok{model.matrix}\NormalTok{(modelo)}
\NormalTok{qr\_decomp }\OtherTok{\textless{}{-}} \FunctionTok{qr}\NormalTok{(X)}
\NormalTok{y }\OtherTok{\textless{}{-}}\NormalTok{ cheddar}\SpecialCharTok{$}\NormalTok{taste}

\CommentTok{\# Resolver el sistema utilizando la función \textquotesingle{}qr.coef\textquotesingle{} que aplica la descomposición QR para resolver el sistema}
\NormalTok{coeficientes\_qr }\OtherTok{\textless{}{-}} \FunctionTok{qr.coef}\NormalTok{(qr\_decomp, y)}


\FunctionTok{print}\NormalTok{(coeficientes\_qr)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## (Intercept)      Acetic         H2S      Lactic 
## -28.8767696   0.3277413   3.9118411  19.6705434
\end{verbatim}

\hypertarget{ejercicio-7-cap.-2-puxe1g.-31}{%
\subsection{7. (Ejercicio 7 cap. 2 pág.
31)}\label{ejercicio-7-cap.-2-puxe1g.-31}}

An experiment was conducted to determine the effect of four factors on
the resistivity of a semiconductor wafer. The data is found in wafer
where each of the four factors is coded as − or + depending on whether
the low or the high setting for that factor was used. Fit the linear
model resist \textasciitilde{} x1 + x2 + x3 + x4.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(wafer)}
\NormalTok{modelo }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(resist }\SpecialCharTok{\textasciitilde{}}\NormalTok{ x1 }\SpecialCharTok{+}\NormalTok{ x2 }\SpecialCharTok{+}\NormalTok{ x3 }\SpecialCharTok{+}\NormalTok{ x4, }\AttributeTok{data =}\NormalTok{ wafer)}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\tightlist
\item
  Extract the X matrix using the model.matrix function. Examine this to
  determine how the low and high levels have been coded in the model.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{X }\OtherTok{\textless{}{-}} \FunctionTok{model.matrix}\NormalTok{(modelo)}
\NormalTok{X}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    (Intercept) x1+ x2+ x3+ x4+
## 1            1   0   0   0   0
## 2            1   1   0   0   0
## 3            1   0   1   0   0
## 4            1   1   1   0   0
## 5            1   0   0   1   0
## 6            1   1   0   1   0
## 7            1   0   1   1   0
## 8            1   1   1   1   0
## 9            1   0   0   0   1
## 10           1   1   0   0   1
## 11           1   0   1   0   1
## 12           1   1   1   0   1
## 13           1   0   0   1   1
## 14           1   1   0   1   1
## 15           1   0   1   1   1
## 16           1   1   1   1   1
## attr(,"assign")
## [1] 0 1 2 3 4
## attr(,"contrasts")
## attr(,"contrasts")$x1
## [1] "contr.treatment"
## 
## attr(,"contrasts")$x2
## [1] "contr.treatment"
## 
## attr(,"contrasts")$x3
## [1] "contr.treatment"
## 
## attr(,"contrasts")$x4
## [1] "contr.treatment"
\end{verbatim}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  Compute the correlation in the X matrix. Why are there some missing
  values in the matrix?
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{correlation\_X }\OtherTok{\textless{}{-}} \FunctionTok{cor}\NormalTok{(X)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in cor(X): the standard deviation is zero
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{correlation\_X}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##             (Intercept) x1+ x2+ x3+ x4+
## (Intercept)           1  NA  NA  NA  NA
## x1+                  NA   1   0   0   0
## x2+                  NA   0   1   0   0
## x3+                  NA   0   0   1   0
## x4+                  NA   0   0   0   1
\end{verbatim}

Hay valores missing porque está incluyendo el intercepto que es
constante

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
  What difference in resistance is expected when moving from the low to
  the high level of x1?
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{coeficientes }\OtherTok{\textless{}{-}} \FunctionTok{coef}\NormalTok{(modelo)}
\NormalTok{diferencia\_resistencia\_x1 }\OtherTok{\textless{}{-}}\NormalTok{ coeficientes[}\StringTok{"x1+"}\NormalTok{]}
\FunctionTok{print}\NormalTok{(diferencia\_resistencia\_x1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     x1+ 
## 25.7625
\end{verbatim}

La diferencia de resistencia será de 15,76

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{3}
\tightlist
\item
  Refit the model without x4 and examine the regression coefficients and
  standard errors? What stayed the the same as the original fit and what
  changed?
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{modelo\_sin\_x4 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(resist }\SpecialCharTok{\textasciitilde{}}\NormalTok{ x1 }\SpecialCharTok{+}\NormalTok{ x2 }\SpecialCharTok{+}\NormalTok{ x3, }\AttributeTok{data =}\NormalTok{ wafer)}
\FunctionTok{summary}\NormalTok{(modelo\_sin\_x4)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = resist ~ x1 + x2 + x3, data = wafer)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -36.137 -20.550   3.575  18.463  41.012 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)   229.54      13.32  17.231 7.88e-10 ***
## x1+            25.76      13.32   1.934 0.077047 .  
## x2+           -69.89      13.32  -5.246 0.000206 ***
## x3+            43.59      13.32   3.272 0.006677 ** 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 26.64 on 12 degrees of freedom
## Multiple R-squared:  0.7777, Adjusted R-squared:  0.7221 
## F-statistic: 13.99 on 3 and 12 DF,  p-value: 0.0003187
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(modelo)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = resist ~ x1 + x2 + x3 + x4, data = wafer)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -43.381 -17.119   4.825  16.644  33.769 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)   236.78      14.77  16.032 5.65e-09 ***
## x1+            25.76      13.21   1.950 0.077085 .  
## x2+           -69.89      13.21  -5.291 0.000256 ***
## x3+            43.59      13.21   3.300 0.007083 ** 
## x4+           -14.49      13.21  -1.097 0.296193    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 26.42 on 11 degrees of freedom
## Multiple R-squared:  0.7996, Adjusted R-squared:  0.7267 
## F-statistic: 10.97 on 4 and 11 DF,  p-value: 0.0007815
\end{verbatim}

Los que cambió fue el intercepto, los valores de R cuadrado y el error
estándar residual. No cambiaron los coeficientes de las variables
restantes.

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{4}
\tightlist
\item
  Explain how the change in the regression coefficients is related to
  the correlation matrix of X.
\end{enumerate}

\hypertarget{ejercicios-del-libro-de-carmona}{%
\section{Ejercicios del libro de
Carmona}\label{ejercicios-del-libro-de-carmona}}

\hypertarget{ejercicio-2.1-del-capuxedtulo-2-puxe1gina-41}{%
\subsection{1. (Ejercicio 2.1 del Capítulo 2 página
41)}\label{ejercicio-2.1-del-capuxedtulo-2-puxe1gina-41}}

Una variable Y toma los valores y1, y2 y y3 en función de otra variable
X con los valores x1, x2 y x3. Determinar cuales de los siguientes
modelos son lineales y encontrar, en su caso, la matriz de diseño para
x1 = 1, x2 = 2 y x3 = 3.

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\tightlist
\item
  Sí es lineal porque los estimadores tienen una relaión lineal con las
  variables. La matriz de diseño es:
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{X }\OtherTok{\textless{}{-}}\FunctionTok{matrix}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\FloatTok{1.}\NormalTok{, }\FloatTok{1.}\NormalTok{, }\DecValTok{0}\NormalTok{, }\FloatTok{1.}\NormalTok{, }\FloatTok{2.}\NormalTok{, }\FloatTok{3.}\NormalTok{,}\FloatTok{1.}\NormalTok{, }\FloatTok{3.}\NormalTok{, }\FloatTok{8.}\NormalTok{), }\AttributeTok{nrow =} \DecValTok{3}\NormalTok{, }\AttributeTok{byrow =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{X}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      [,1] [,2] [,3]
## [1,]    1    1    0
## [2,]    1    2    3
## [3,]    1    3    8
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  No es lineal porque los estimadores no tienen una relación lineal con
  las variables
\end{enumerate}

c)No es lineal porque los estimadores no tienen una relación lineal con
las variables

\hypertarget{ejercicio-2.4-del-capuxedtulo-2-puxe1gina-42}{%
\subsection{2. (Ejercicio 2.4 del Capítulo 2 página
42)}\label{ejercicio-2.4-del-capuxedtulo-2-puxe1gina-42}}

Cuatro objetos cuyos pesos exactos son b1, b2, b3 y b4 han sido pesados
en una balanza de platillos de acuerdo con el siguiente esquema:

Hallar las estimaciones de cada bi y de la varianza del error.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Crear la matriz de diseño X y el vector de respuesta y}
\NormalTok{X }\OtherTok{\textless{}{-}} \FunctionTok{matrix}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{, }
              \DecValTok{1}\NormalTok{, }\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{,}
              \DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{, }\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{,}
              \DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{, }\DecValTok{0}\NormalTok{, }\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{,}
              \DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{,}
              \DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{, }\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{), }
            \AttributeTok{nrow =} \DecValTok{6}\NormalTok{, }\AttributeTok{byrow =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{y }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\FloatTok{9.2}\NormalTok{, }\FloatTok{8.3}\NormalTok{, }\FloatTok{5.4}\NormalTok{, }\SpecialCharTok{{-}}\FloatTok{1.6}\NormalTok{, }\FloatTok{8.7}\NormalTok{, }\FloatTok{3.5}\NormalTok{)}

\CommentTok{\# Creo el modelo sin interceptoo y obtengo coeficientes y varianza }
\NormalTok{modelo }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(y }\SpecialCharTok{\textasciitilde{}}\NormalTok{ X }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{)  }
\NormalTok{estimaciones }\OtherTok{\textless{}{-}} \FunctionTok{coef}\NormalTok{(modelo)}
\NormalTok{varianza\_error }\OtherTok{\textless{}{-}} \FunctionTok{summary}\NormalTok{(modelo)}\SpecialCharTok{$}\NormalTok{sigma}\SpecialCharTok{\^{}}\DecValTok{2}
\FunctionTok{print}\NormalTok{(estimaciones)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        X1        X2        X3        X4 
## 2.0685714 0.5342857 2.9400000 3.6685714
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(varianza\_error)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.08371429
\end{verbatim}

\end{document}
